Feature/coin algo
CoolBitX-Technology/coolwallet-signing-tools pull request #139
Opened 2022-08-03 07:38 UTC by beno-accubits

2022-08-10 01:51 UTC, hank121314 requested changes

2022-08-10 01:51 UTC, hank121314 commented on script-generator/.gitignore
> +
Unrelated changes.

2022-08-11 01:31 UTC, hank121314 requested changes

2022-08-11 01:31 UTC, hank121314 commented on script-generator/.gitignore
> +>>>>>>> dev
Unrelated change.

2022-08-12 01:20 UTC, hank121314 approved these changes

2022-08-12 02:26 UTC, hankliu418 approved these changes

2022-08-12 02:26 UTC, merged