Feat/polygon script
CoolBitX-Technology/coolwallet-signing-tools pull request #42
Opened 2022-01-26 03:48 UTC by Sotatek-Chung

2022-02-11 04:02 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:02 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:02 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:02 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:03 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:03 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:03 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:03 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:09 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .showMessage("POLYGON")
should display symbol "MATIC"

2022-02-11 04:13 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .rlpList(1)
rlpList is deprecated function

2022-02-11 04:14 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +      .rlpList(2)
rlpList is deprecated function

2022-02-11 04:15 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +    ScriptData argChainId = sac.getArgumentRightJustified(2);
redundant argument

2022-02-11 06:34 UTC, hankliu418 requested changes
Please update the issue below, thanks.

2022-02-15 09:27 UTC, hankliu418 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +  }
missing end "}"

2022-02-16 07:40 UTC, hankliu418 requested changes
Please remove redundant argument in line 320, thanks.

2022-02-16 08:22 UTC, Sotatek-Chung commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/PolyScript.java
> +    ScriptData argChainId = sac.getArgumentRightJustified(2);
we removed it.

2022-03-03 03:10 UTC, hank121314 approved these changes

2022-03-10 09:28 UTC, srt1678 approved these changes

2022-03-11 09:20 UTC, merged