feat(Terra): CW-5715- Terra Normal transfer
CoolBitX-Technology/coolwallet-signing-tools pull request #69
Opened 2022-03-17 09:17 UTC by kanitsu

Add Terra normal transfer script, with parameterized tx and fee denom.

2022-03-17 09:17 UTC, cbx-tech commented
Task linked: [CW-5715 [SDK] Terra SDK - Terra normal transfer](https://app.clickup.com/t/25577573/CW-5715)

2022-03-17 09:43 UTC, skchang0710 requested changes

2022-03-17 09:43 UTC, skchang0710 commented on script-generator/src/main/java/com/coolbitx/wallet/signing/scriptlib/TerraScript.java
> +                        new ScriptAssembler().copyString(HexUtil.toHexString("@"), Buffer.CACHE2).getScript())
should be considered throwing error while signature verification failure

2022-03-18 03:23 UTC, hank121314 approved these changes

2022-03-18 03:32 UTC, skchang0710 approved these changes

2022-03-18 03:33 UTC, merged