Avax C-Chain Script
CoolBitX-Technology/coolwallet-signing-tools pull request #72
Opened 2022-03-18 04:31 UTC by cyje66

2022-03-29 01:53 UTC, hank121314 requested changes

2022-03-29 01:53 UTC, hank121314 commented on .gitignore
> +script-generator/local-lib
Unrelated changes.
The `.idea` should be in your global gitignore.

2022-03-29 01:53 UTC, hank121314 commented on script-generator/pom.xml
> -        <!--        <dependency>
Unrelated changes.

2022-03-29 03:20 UTC, hank121314 requested changes
Please make sure your PR does not contain any changes except `.java` files.

2022-03-29 03:20 UTC, hank121314 commented on .gitignore
> +/bin/
Add new line EOF.

2022-03-29 03:20 UTC, hank121314 commented on script-generator/pom.xml
> +</project>
Add new line EOF.

2022-03-29 03:21 UTC, cyje66 commented on .gitignore
> +/bin/
ok!

2022-04-11 09:09 UTC, hank121314 approved these changes

2022-04-14 03:45 UTC, hankliu418 approved these changes

2022-04-14 04:00 UTC, merged